/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: '#0D1117',
        surface: '#161B22',
        'surface-light': '#21262D',
        card: '#1C2128',
        'card-elevated': '#252C35',
        border: '#30363D',
        'border-light': '#21262D',
        'border-focus': '#58A6FF',
        fg1: '#C9D1D9',
        fg2: '#8B949E',
        fg3: '#6E7681',
        'fg-disabled': '#484F58',
        primary: '#FF9500',
        'primary-light': '#FFAD33',
        'primary-dark': '#E68600',
        'accent-cyan': '#00FFD1',
        'accent-hud': '#00D4FF',
        'accent-blue': '#58A6FF',
        'accent-green': '#3FB950',
        'accent-purple': '#BC8CFF',
        es: '#FFC107',
        ea: '#F44336',
        ep: '#4CAF50',
        spectrum: '#9C27B0',
        radar: '#00BCD4',
        drone: '#FF5722',
        gps: '#3F51B5',
        radio: '#7B68EE',
        sop: '#607D8B',
        success: '#3FB950',
        warning: '#D29922',
        error: '#F85149',
        info: '#58A6FF',
        'success-bg': '#1F3D2A',
        'warning-bg': '#3D3215',
        'error-bg': '#3D1F1F',
        'info-bg': '#1F3D4D',
      },
      fontFamily: {
        sans: ['Sarabun', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'Menlo', 'monospace'],
      },
      animation: {
        'live-pulse': 'livePulse 1.2s ease-in-out infinite',
        'bubble-in': 'bubbleIn 0.4s cubic-bezier(0.34,1.56,0.64,1) both',
      },
      keyframes: {
        livePulse: {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.4', transform: 'scale(0.8)' },
        },
        bubbleIn: {
          '0%': { opacity: '0', transform: 'scale(0)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
